### ISSUE TITLE
ImportError: No module named authorization

### ISSUE THREAD

**Issue by linuxelf001** [tamcclur/AzureARMRecovery#1]
**_Shell:_** Bash on Ubuntu on Windows

python main.py sub-id test-server test-server
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from azure.mgmt.authorization import AuthorizationManagementClient, AuthorizationManagementClientConfiguration
ImportError: No module named authorization

_

> 404 Registry returned 404 for GET on https://registry.npmjs.org/azure-authorization

_

**Comment by tamcclur** [comment]
Fixed this issue in 54f8b7b and 64b4c1a

Issue was my development environment was not as sterile as I thought, and some packages were not in requirements.txt

I also had to modify some main.py code to account for updated Azure Python SDK modules
